import { useCallback, useEffect, useMemo, useState } from 'react'
import { eventMatchesDate } from '../lib/calendar-events'
import { nextOccurrence, toISODate } from '../lib/dates'
import { occursOn } from '../lib/recurrence'
import { createCalendarEvent, createCountdown, createCourse, createExam, createNote, createRecurringReminder, createSelfSchedule, createTerm, createTodo, emptyData, exportBlob, loadData, parseImport, saveData } from '../lib/store'
import type { AppData, CalendarEvent, Countdown, Course, Exam, Note, Priority, RecurringReminder, ReminderSettings, SelfScheduleItem, Term, TimetableViewSettings, Todo } from '../types'
function withTombstones(prev: AppData, ids: string[]): AppData {
  const now = Date.now()
  const extra = ids.map((id) => ({ id, deletedAt: now }))
  return { ...prev, tombstones: [...(prev.tombstones ?? []).filter((item) => !ids.includes(item.id)), ...extra] }
}
export function useAppStore(){
 const[data,setData]=useState<AppData>(emptyData);const[ready,setReady]=useState(false);useEffect(()=>{setData(loadData());setReady(true)},[]);useEffect(()=>{if(ready)saveData(data)},[data,ready]);useEffect(()=>{const refresh=()=>setData(loadData());window.addEventListener('days-data-changed',refresh);return()=>window.removeEventListener('days-data-changed',refresh)},[]);const replace=useCallback((next:AppData)=>setData(next),[])
 const addTodo=useCallback((title:string,extras?:{dueDate?:string;dueTime?:string;dueEndTime?:string;priority?:Priority;remindMinutes?:number})=>{const item=createTodo(title,extras);if(!item.title)return;setData(p=>({...p,todos:[item,...p.todos]}))},[]);const toggleTodo=useCallback((id:string)=>setData(p=>({...p,todos:p.todos.map(t=>t.id===id?{...t,done:!t.done}:t)})),[]);const updateTodo=useCallback((id:string,patch:Partial<Todo>)=>setData(p=>({...p,todos:p.todos.map(t=>t.id===id?{...t,...patch}:t)})),[]);const removeTodo=useCallback((id:string)=>setData(p=>({...withTombstones(p,[id]),todos:p.todos.filter(t=>t.id!==id)})),[])
 const addCountdown=useCallback((title:string,date:string,extras?:{color?:string;emoji?:string;repeatYearly?:boolean})=>{const item=createCountdown(title,date,extras);if(!item.title||!item.date)return;setData(p=>({...p,countdowns:[...p.countdowns,item]}))},[]);const updateCountdown=useCallback((id:string,patch:Partial<Countdown>)=>setData(p=>({...p,countdowns:p.countdowns.map(c=>c.id===id?{...c,...patch}:c)})),[]);const removeCountdown=useCallback((id:string)=>setData(p=>({...withTombstones(p,[id]),countdowns:p.countdowns.filter(c=>c.id!==id)})),[])
 const addNote=useCallback((title:string,body:string,extras?:{color?:string;date?:string})=>{const item=createNote(title,body,extras);if(!item.title&&!item.body.trim())return;setData(p=>({...p,notes:[item,...p.notes]}))},[]);const updateNote=useCallback((id:string,patch:Partial<Note>)=>setData(p=>({...p,notes:p.notes.map(n=>n.id===id?{...n,...patch,updatedAt:Date.now()}:n)})),[]);const removeNote=useCallback((id:string)=>setData(p=>({...withTombstones(p,[id]),notes:p.notes.filter(n=>n.id!==id)})),[])
 const addCourse=useCallback((name:string,extras?:Partial<Omit<Course,'id'|'name'|'createdAt'>>)=>setData(p=>{const item=createCourse(name,{...extras,termId:extras?.termId??p.currentTermId});return item.name?{...p,courses:[...p.courses,item]}:p}),[]);const addCourses=useCallback((items:Course[])=>{if(items.length)setData(p=>({...p,courses:[...p.courses,...items.map(c=>({...c,termId:c.termId||p.currentTermId}))]}))},[]);const updateCourse=useCallback((id:string,patch:Partial<Course>)=>setData(p=>({...p,courses:p.courses.map(c=>c.id===id?{...c,...patch}:c)})),[]);const removeCourse=useCallback((id:string)=>setData(p=>({...withTombstones(p,[id]),courses:p.courses.filter(c=>c.id!==id)})),[]);const clearCourses=useCallback(()=>setData(p=>({...withTombstones(p,p.courses.map(c=>c.id)),courses:[]})),[])
 const addExam=useCallback((name:string,extras?:Partial<Omit<Exam,'id'|'name'|'createdAt'>>)=>{const item=createExam(name,extras);if(!item.name||!item.date)return;setData(p=>({...p,exams:[...p.exams,item].sort((a,b)=>a.date.localeCompare(b.date))}))},[]);const addExams=useCallback((items:Exam[])=>{if(items.length)setData(p=>({...p,exams:[...p.exams,...items].sort((a,b)=>a.date.localeCompare(b.date))}))},[]);const updateExam=useCallback((id:string,patch:Partial<Exam>)=>setData(p=>({...p,exams:p.exams.map(e=>e.id===id?{...e,...patch}:e)})),[]);const removeExam=useCallback((id:string)=>setData(p=>({...withTombstones(p,[id]),exams:p.exams.filter(e=>e.id!==id)})),[])
 const addSelfSchedule=useCallback((title:string,extras?:Partial<Omit<SelfScheduleItem,'id'|'title'|'createdAt'>>)=>setData(p=>{const item=createSelfSchedule(title,extras);return item.title?{...p,selfSchedules:[...p.selfSchedules,item]}:p}),[]);const updateSelfSchedule=useCallback((id:string,patch:Partial<SelfScheduleItem>)=>setData(p=>({...p,selfSchedules:p.selfSchedules.map(s=>s.id===id?{...s,...patch}:s)})),[]);const addSelfSchedules=useCallback((items:SelfScheduleItem[])=>{if(items.length)setData(p=>({...p,selfSchedules:[...p.selfSchedules,...items]}))},[]);const removeSelfSchedule=useCallback((id:string)=>setData(p=>({...withTombstones(p,[id]),selfSchedules:p.selfSchedules.filter(s=>s.id!==id)})),[]);const clearSelfSchedules=useCallback(()=>setData(p=>({...withTombstones(p,p.selfSchedules.map(s=>s.id)),selfSchedules:[]})),[]);const addCalendarEvent=useCallback((title:string,extras?:Partial<Omit<CalendarEvent,'id'|'title'|'createdAt'>>)=>setData(p=>{const item=createCalendarEvent(title,extras);return item.title&&item.date?{...p,calendarEvents:[...p.calendarEvents,item]}:p}),[]);const updateCalendarEvent=useCallback((id:string,patch:Partial<CalendarEvent>)=>setData(p=>({...p,calendarEvents:p.calendarEvents.map(e=>e.id===id?{...e,...patch}:e)})),[]);const removeCalendarEvent=useCallback((id:string)=>setData(p=>({...withTombstones(p,[id]),calendarEvents:p.calendarEvents.filter(e=>e.id!==id)})),[])
 const addRecurringReminder=useCallback((title:string,extras?:Partial<Omit<RecurringReminder,'id'|'title'|'createdAt'|'updatedAt'>>)=>setData(p=>{const item=createRecurringReminder(title,extras);return item.title&&item.startDate?{...p,recurringReminders:[item,...p.recurringReminders]}:p}),[]);const updateRecurringReminder=useCallback((id:string,patch:Partial<RecurringReminder>)=>setData(p=>({...p,recurringReminders:p.recurringReminders.map(r=>r.id===id?{...r,...patch,updatedAt:Date.now()}:r)})),[]);const removeRecurringReminder=useCallback((id:string)=>setData(p=>({...withTombstones(p,[id]),recurringReminders:p.recurringReminders.filter(r=>r.id!==id)})),[])
 const updateReminderSettings=useCallback((patch:Partial<ReminderSettings>)=>setData(p=>({...p,reminderSettings:{...p.reminderSettings,...patch}})),[]);const currentTerm=useMemo(()=>data.terms.find(t=>t.id===data.currentTermId)??data.terms[0],[data.currentTermId,data.terms]);const setTermStart=useCallback((termStart?:string)=>setData(p=>({...p,termStart:termStart||undefined,terms:p.terms.map(t=>t.id===p.currentTermId?{...t,startDate:termStart||''}:t)})),[]);const addTerm=useCallback((extras?:Partial<Term>)=>setData(p=>{const term=createTerm(extras);return{...p,terms:[...p.terms,term],currentTermId:term.id,termStart:term.startDate||undefined}}),[]);const updateTerm=useCallback((id:string,patch:Partial<Term>)=>setData(p=>{const terms=p.terms.map(t=>t.id===id?{...t,...patch}:t),current=terms.find(t=>t.id===p.currentTermId);return{...p,terms,termStart:current?.startDate||undefined}}),[]);const removeTerm=useCallback((id:string)=>setData(p=>{if(p.terms.length<=1)return p;const terms=p.terms.filter(t=>t.id!==id),currentTermId=p.currentTermId===id?terms[0].id:p.currentTermId,current=terms.find(t=>t.id===currentTermId);const dropped=p.courses.filter(c=>c.termId===id).map(c=>c.id);return{...withTombstones(p,dropped),terms,courses:p.courses.filter(c=>c.termId!==id),currentTermId,termStart:current?.startDate||undefined}}),[]);const setCurrentTerm=useCallback((id:string)=>setData(p=>{const current=p.terms.find(t=>t.id===id);return current?{...p,currentTermId:id,termStart:current.startDate||undefined}:p}),[])
 const updateTimetableView=useCallback((patch:Partial<TimetableViewSettings>)=>setData(p=>({...p,timetableView:{...p.timetableView,...patch}})),[]);const toggleHiddenHour=useCallback((hour:number)=>setData(p=>{const hidden=new Set(p.timetableView.hiddenHours);if(hidden.has(hour))hidden.delete(hour);else hidden.add(hour);if(hidden.size>=24)return p;return{...p,timetableView:{...p.timetableView,hiddenHours:[...hidden].sort((a,b)=>a-b)}}}),[]);const toggleHiddenWeekday=useCallback((weekday:number)=>setData(p=>{const hidden=new Set(p.timetableView.hiddenWeekdays);if(hidden.has(weekday))hidden.delete(weekday);else hidden.add(weekday);if(hidden.size>=7)return p;return{...p,timetableView:{...p.timetableView,hiddenWeekdays:[...hidden].sort((a,b)=>a-b)}}}),[])
 const clearAll=useCallback(()=>setData(emptyData()),[]);const downloadBackup=useCallback(()=>{const blob=exportBlob(data),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`kemiao-days-${toISODate(new Date())}.json`;a.click();URL.revokeObjectURL(url)},[data]);const importBackup=useCallback(async(file:File)=>replace(parseImport(await file.text())),[replace]);const itemsOnDate=useCallback((iso:string)=>({todos:data.todos.filter(t=>t.dueDate===iso),countdowns:data.countdowns.filter(c=>nextOccurrence(c.date,c.repeatYearly)===iso||c.date===iso),notes:data.notes.filter(n=>n.date===iso),exams:data.exams.filter(e=>e.date===iso),events:data.calendarEvents.filter(e=>eventMatchesDate(e,iso)),recurring:data.recurringReminders.filter(r=>occursOn(r,iso))}),[data]);const stats=useMemo(()=>({remaining:data.todos.filter(t=>!t.done).length,countdownCount:data.countdowns.length,noteCount:data.notes.length,courseCount:data.courses.length,examCount:data.exams.length,eventCount:data.calendarEvents.length}),[data])
 return{data,ready,stats,addTodo,toggleTodo,updateTodo,removeTodo,addCountdown,updateCountdown,removeCountdown,addNote,updateNote,removeNote,addCourse,addCourses,updateCourse,removeCourse,clearCourses,addExam,addExams,updateExam,removeExam,addSelfSchedule,addSelfSchedules,updateSelfSchedule,removeSelfSchedule,clearSelfSchedules,addCalendarEvent,updateCalendarEvent,removeCalendarEvent,addRecurringReminder,updateRecurringReminder,removeRecurringReminder,currentTerm,updateReminderSettings,setTermStart,addTerm,updateTerm,removeTerm,setCurrentTerm,updateTimetableView,toggleHiddenHour,toggleHiddenWeekday,clearAll,downloadBackup,importBackup,itemsOnDate,replace}
}
export type AppStore=ReturnType<typeof useAppStore>
