import { useMemo, useState } from 'react'
import type { CSSProperties } from 'react'
import type { AppStore } from '../hooks/useAppStore'
import { EXAM_KIND_LABEL } from '../types'
import { WEEKDAY_LABELS, normalizeClockInput } from '../lib/periods'
import { startOfWeek, shiftWeek } from '../lib/week-grid'
import { importTimetableAny } from '../lib/import-any'
import { TIMETABLE_ACCEPT } from '../lib/file-kinds'
const HOUR=64
const top=(time:string)=>{const [h,m]=time.split(':').map(Number);return h*HOUR+(m/60)*HOUR}
const iso=(d:Date)=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`
export default function ExamTimetable({store}:{store:AppStore}){
 const [week,setWeek]=useState(()=>startOfWeek(new Date(),1)),[name,setName]=useState(''),[date,setDate]=useState(''),[start,setStart]=useState('09:00'),[end,setEnd]=useState('11:00'),[location,setLocation]=useState(''),[status,setStatus]=useState(''),[selected,setSelected]=useState<string>();
 const days=useMemo(()=>Array.from({length:7},(_,i)=>{const d=new Date(week);d.setDate(d.getDate()+i);return{weekday:i+1,date:d}}),[week]);const exams=store.data.exams
 const add=()=>{const s=normalizeClockInput(start),e=normalizeClockInput(end);if(!name.trim()||!date||!s){setStatus('请填写考试名称、日期和开始时间');return}store.addExam(name,{date,startTime:s,endTime:e||undefined,location:location||undefined});setName('');setStatus(`已添加 ${name.trim()}`)}
 const importFile=async(file:File)=>{setStatus('正在识别考试时间表…');try{const r=await importTimetableAny(file,{classRemindMinutes:store.data.reminderSettings.classDefaultMinutes,examRemindMinutes:store.data.reminderSettings.examDefaultMinutes},'这是大学考试时间表，请重点识别考试名称、日期、开始结束时间、地点、座位和考试类型。');if(r.exams.length)store.addExams(r.exams);setStatus(`已识别并导入 ${r.exams.length} 场考试${r.warnings.length?'；'+r.warnings.slice(0,2).join('；'):''}`)}catch(e){setStatus(e instanceof Error?e.message:'识别失败')}}
 return <section className="view"><header className="view-head"><h2>考试时间表</h2><p className="muted">横向星期、纵向具体时间；考试也像课程一样落在时间轴上。支持图片、截图、Excel、CSV 等导入识别。</p></header>
 <div className="card"><div className="row wrap"><button className="btn ghost" onClick={()=>setWeek(d=>shiftWeek(d,-1))}>上一周</button><strong>{week.getFullYear()} / {week.getMonth()+1} / {week.getDate()} 起</strong><button className="btn ghost" onClick={()=>setWeek(d=>shiftWeek(d,1))}>下一周</button><button className="btn ghost" onClick={()=>setWeek(startOfWeek(new Date(),1))}>本周</button><label className="btn primary file-btn">导入考试图片/文件<input hidden type="file" accept={TIMETABLE_ACCEPT} onChange={e=>{const f=e.target.files?.[0];if(f)void importFile(f);e.target.value='' }}/></label></div>{status&&<p className="import-status">{status}</p>}</div>
 <div className="card"><div className="row wrap"><input className="input" placeholder="考试名称" value={name} onChange={e=>setName(e.target.value)}/><input className="input slim" type="date" value={date} onChange={e=>setDate(e.target.value)}/><input className="input slim" value={start} onChange={e=>setStart(e.target.value)} placeholder="09:00"/><input className="input slim" value={end} onChange={e=>setEnd(e.target.value)} placeholder="11:00"/><input className="input slim" placeholder="地点" value={location} onChange={e=>setLocation(e.target.value)}/><button className="btn primary" onClick={add}>添加考试</button></div></div>
 <div className="tt-wrap card"><div className="exam-grid" style={{'--exam-hour':`${HOUR}px`} as CSSProperties}><div className="exam-grid-head"><div>时间</div>{days.map(d=><div key={d.weekday}>{WEEKDAY_LABELS[d.weekday-1]}<small>{d.date.getMonth()+1}/{d.date.getDate()}</small></div>)}</div><div className="exam-grid-body"><div className="exam-time-axis">{Array.from({length:24},(_,h)=><span key={h} style={{top:h*HOUR}}>{String(h).padStart(2,'0')}:00</span>)}</div>{days.map(d=><div className="exam-day" key={d.weekday}>{Array.from({length:24},(_,h)=><i key={h} style={{top:h*HOUR}}/>)}{exams.filter(e=>e.date===iso(d.date)).map(e=><button key={e.id} className={`exam-block ${selected===e.id?'is-selected':''}`} style={{top:top(e.startTime),height:Math.max(48,(top(e.endTime||e.startTime)-top(e.startTime))||64)}} onClick={()=>setSelected(e.id)}><strong>{EXAM_KIND_LABEL[e.kind]} · {e.name}</strong><span>{e.startTime}{e.endTime?`-${e.endTime}`:''}</span><span>{e.location||'地点未填写'}{e.seat?` · ${e.seat}`:''}</span></button>)}</div>)}</div></div></div>
 {selected&&(()=>{const e=exams.find(x=>x.id===selected);if(!e)return null;return <div className="card week-detail"><div><p className="kicker">{e.date} · {EXAM_KIND_LABEL[e.kind]}</p><h3>{e.name}</h3><p className="muted">{e.startTime}{e.endTime?`-${e.endTime}`:''} · {e.location||'地点未填写'}{e.seat?` · 座位 ${e.seat}`:''}</p></div><div className="row wrap"><button className="btn ghost" onClick={()=>{store.removeExam(e.id);setSelected(undefined)}}>删除</button><button className="btn ghost" onClick={()=>setSelected(undefined)}>关闭</button></div></div>})()}
 </section>
}
