import { useEffect, useMemo, useState } from 'react'
import type { AppStore } from '../hooks/useAppStore'
import type { DueReminder } from '../lib/reminders'
import { daysUntil, toISODate, startOfToday } from '../lib/dates'
import { WEEKDAY_LABELS, durationMinutes, formatDuration, normalizeClockInput, setPeriodTable } from '../lib/periods'
import { TIMETABLE_ACCEPT } from '../lib/file-kinds'
import { importTimetableAny } from '../lib/import-any'
import { upcomingExams } from '../lib/reminders'
import { sampleExamCsv, sampleGridCsv, type TimetableImportResult } from '../lib/timetable-import'
import { termLabel } from '../lib/terms'
import { courseInTeachingWeek, courseInTerm, shiftWeek, startOfWeek, teachingWeekNumber, weekRangeLabel, weekStartForTeachingWeek } from '../lib/week-grid'
import { EXAM_KIND_LABEL, type Course, type ExamKind } from '../types'
import ScheduleSettings from './ScheduleSettings'
import WeekTimetable from './WeekTimetable'

function TimeInput({ value, onChange, label }: { value:string; onChange:(next:string)=>void; label:string }) {
  return <input className="input slim" type="text" inputMode="numeric" placeholder="08:00" value={value} aria-label={label} onChange={(e)=>onChange(e.target.value)} onBlur={()=>{const parsed=normalizeClockInput(value); if(parsed) onChange(parsed)}} />
}
type Tab = 'week'|'import'|'exams'|'remind'

export default function Schedule({ store, requestPermission, previewReminder }: { store:AppStore; requestPermission:()=>Promise<NotificationPermission|'denied'|'granted'>; previewReminder:(item:DueReminder)=>void }) {
  const [tab,setTab]=useState<Tab>('week'), [name,setName]=useState(''), [weekday,setWeekday]=useState(1), [startTime,setStartTime]=useState('08:00'), [endTime,setEndTime]=useState('09:40'), [location,setLocation]=useState(''), [teacher,setTeacher]=useState(''), [status,setStatus]=useState(''), [importing,setImporting]=useState(false), [review,setReview]=useState<TimetableImportResult|null>(null), [previewUrl,setPreviewUrl]=useState(''), [userHint,setUserHint]=useState(''), [weekMonday,setWeekMonday]=useState(()=>startOfWeek(new Date(),1)), [now,setNow]=useState(()=>new Date()), [selectedId,setSelectedId]=useState<string>(), [showAdd,setShowAdd]=useState(false), [settingsOpen,setSettingsOpen]=useState(false)
  const [examName,setExamName]=useState(''), [examKind,setExamKind]=useState<ExamKind>('final'), [examDate,setExamDate]=useState(''), [examStart,setExamStart]=useState('09:00'), [examEnd,setExamEnd]=useState('11:00'), [examLoc,setExamLoc]=useState('')
  const todayISO=toISODate(startOfToday()), settings=store.data.reminderSettings, view=store.data.timetableView, currentTerm=store.currentTerm, thisWeekStart=startOfWeek(now,view.weekStartsOn), weekNo=teachingWeekNumber(weekMonday,currentTerm?.startDate,view.weekStartsOn)
  const termCourses=useMemo(()=>store.data.courses.filter(c=>courseInTerm(c,store.data.currentTermId)),[store.data.courses,store.data.currentTermId])
  const visibleCourses=useMemo(()=>termCourses.filter(c=>courseInTeachingWeek(c,weekNo)||view.showOffWeekCourses),[termCourses,view.showOffWeekCourses,weekNo])
  const offWeekIds=useMemo(()=>{const ids=new Set<string>(); if(!view.showOffWeekCourses)return ids; for(const c of termCourses)if(!courseInTeachingWeek(c,weekNo))ids.add(c.id); return ids},[termCourses,view.showOffWeekCourses,weekNo])
  const selected=store.data.courses.find(c=>c.id===selectedId)
  useEffect(()=>{setWeekMonday(prev=>startOfWeek(prev,view.weekStartsOn))},[view.weekStartsOn])
  useEffect(()=>{const timer=window.setInterval(()=>setNow(new Date()),60000); return()=>window.clearInterval(timer)},[])
  const examsSoon=upcomingExams(store.data.exams,todayISO)
  const addManual=()=>{if(!name.trim())return; const start=normalizeClockInput(startTime),end=normalizeClockInput(endTime); if(!start||!end){setStatus('请用 24 小时制填写时间，例如 08:00 和 09:40');return} store.addCourse(name,{weekday,startTime:start,endTime:end,location:location||undefined,teacher:teacher||undefined,remindMinutes:settings.classDefaultMinutes}); setName('');setTeacher('');setStatus(`已添加 ${name.trim()}（${formatDuration(start,end)}）`)}
  const addExam=()=>{if(!examName.trim()||!examDate)return; const start=normalizeClockInput(examStart),end=examEnd.trim()?normalizeClockInput(examEnd):undefined;if(!start||(examEnd.trim()&&!end)){setStatus('考试时间请用 24 小时制，例如 14:00-16:00');return}store.addExam(examName,{kind:examKind,date:examDate,startTime:start,endTime:end??undefined,location:examLoc||undefined,remindMinutes:settings.examDefaultMinutes});setExamName('');setStatus(`已登记考试 ${examName.trim()} ${examDate} ${start}${end?`-${end}`:''}`)}
  const tryClassReminder=()=>{const course=store.data.courses[0];previewReminder({id:course?.id||'preview-class',key:`preview-class:${Date.now()}`,title:`上课提醒 · ${course?.name||'高等数学'}`,body:`${course?.startTime||'08:00'}-${course?.endTime||'09:40'} ${course?.location||'教学楼A101'} · 还有 ${settings.classDefaultMinutes} 分钟，现在出发以免迟到`,kind:'class',fireAt:Date.now()});setStatus('已弹出上课提醒条。浏览器通知需先点「允许浏览器通知」。')}
  const tryExamReminder=()=>{const exam=store.data.exams[0];previewReminder({id:exam?.id||'preview-exam',key:`preview-exam:${Date.now()}`,title:`考试提醒 · ${exam?.name||'大学英语'}`,body:`${exam?.date||'今天'} ${exam?.startTime||'14:00'}${exam?.endTime?`-${exam.endTime}`:''} ${exam?.location||''} · 请核对开考时间以免记错错过`,kind:'exam',fireAt:Date.now()});setStatus('已弹出考试提醒条。建议同时打开「考试再提前 60 分钟提醒一次」。')}
  const applyResult=(result:TimetableImportResult,label:string)=>{store.addCourses(result.courses);store.addExams(result.exams);const bits=[result.courses.length?`${result.courses.length} 门课`:'',result.exams.length?`${result.exams.length} 场考试`:''].filter(Boolean);setStatus(`已从「${label}」导入 ${bits.join('、')}`+(result.warnings.length?`。提示：${result.warnings.slice(0,3).join('；')}`:''));setReview(null);if(previewUrl){URL.revokeObjectURL(previewUrl);setPreviewUrl('')}setTab(result.kind==='exams'?'exams':'week')}
  const onImport=async(file:File)=>{setPeriodTable(view.classPeriods);setImporting(true);setStatus('');if(previewUrl)URL.revokeObjectURL(previewUrl);setPreviewUrl(file.type.startsWith('image/')?URL.createObjectURL(file):'');try{const result=await importTimetableAny(file,{classRemindMinutes:settings.classDefaultMinutes,examRemindMinutes:settings.examDefaultMinutes},userHint);if(result.source==='ai'){setReview(result);setStatus(`AI 已识别 ${result.courses.length} 门课`+(result.exams.length?`、${result.exams.length} 场考试`:'')+'。请核对后再写入课表。');setTab('import')}else applyResult(result,file.name)}catch(error){setStatus(error instanceof Error?error.message:'导入失败')}finally{setImporting(false)}}
  const patchReviewCourse=(id:string,patch:Partial<Course>)=>setReview(prev=>prev?{...prev,courses:prev.courses.map(c=>c.id===id?{...c,...patch}:c)}:prev)
  const downloadSample=(kind:'grid'|'exam')=>{const csv=kind==='grid'?sampleGridCsv():sampleExamCsv();const blob=new Blob([csv],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=kind==='grid'?'课表示例-周视图.csv':'考试时间表示例.csv';a.click();URL.revokeObjectURL(url)}

  return <section className="view"><header className="view-head"><h2>超级课程表</h2><p className="muted">课表是一张从 00:00 到 23:59 的表格。点右上角「课表设置」选学年学期、开学周数，并隐藏凌晨等不上课的行。</p></header>
    <div className="tabs">{([['week','周课表'],['import','导入'],['exams','考试时间表'],['remind','提醒']] as const).map(([id,label])=><button key={id} className={`tab ${tab===id?'active':''}`} onClick={()=>setTab(id)}>{label}</button>)}</div>
    {status&&<p className="import-status">{status}</p>}
    {tab==='week'&&<>
      <div className="card week-toolbar"><div className="row wrap"><button className="btn ghost" disabled={Boolean(currentTerm?.startDate&&weekNo!=null&&weekNo<=1)} onClick={()=>setWeekMonday(d=>shiftWeek(d,-1))}>上一周</button><div className="week-toolbar-title"><strong>{weekNo!=null?`第 ${weekNo}${currentTerm?` / ${currentTerm.weekCount}`:''} 周`:'周课表'}{weekMonday.getTime()===thisWeekStart.getTime()?' · 本周':''}</strong><span className="muted">{currentTerm?termLabel(currentTerm):''} {weekRangeLabel(weekMonday)}</span></div><button className="btn ghost" disabled={Boolean(currentTerm?.startDate&&weekNo!=null&&weekNo>=currentTerm.weekCount)} onClick={()=>setWeekMonday(d=>shiftWeek(d,1))}>下一周</button><button className="btn ghost" onClick={()=>setWeekMonday(thisWeekStart)}>回到本周</button><button className="btn primary" onClick={()=>setSettingsOpen(true)}>课表设置</button></div>
      <div className="row wrap" style={{marginTop:10}}><button className="btn ghost" onClick={()=>setShowAdd(v=>!v)}>{showAdd?'收起加课':'加一节课'}</button>{termCourses.length===0&&<button className="btn ghost" onClick={()=>{void(async()=>{const res=await fetch(`${import.meta.env.BASE_URL}samples/course-grid.csv`);const blob=await res.blob();await onImport(new File([blob],'course-grid.csv',{type:'text/csv'}))})()}}>载入示例课表</button>}{currentTerm?.startDate?<button className="btn ghost" onClick={()=>setWeekMonday(weekStartForTeachingWeek(currentTerm.startDate,1,view.weekStartsOn))}>第1周</button>:null}</div></div>
      {showAdd&&<div className="card"><div className="row wrap"><input className="input" placeholder="课程名，例如「高等数学」" value={name} onChange={e=>setName(e.target.value)} aria-label="课程名"/><select className="input slim" value={weekday} onChange={e=>setWeekday(Number(e.target.value))}>{WEEKDAY_LABELS.map((label,i)=><option key={label} value={i+1}>{label}</option>)}</select><TimeInput value={startTime} onChange={setStartTime} label="开始时间"/><TimeInput value={endTime} onChange={setEndTime} label="结束时间"/><input className="input slim" placeholder="教室" value={location} onChange={e=>setLocation(e.target.value)}/><input className="input slim" placeholder="老师" value={teacher} onChange={e=>setTeacher(e.target.value)}/><button className="btn primary" onClick={addManual}>加到课表</button></div><p className="muted">当前这节时长 {formatDuration(startTime,endTime)}（{durationMinutes(startTime,endTime)} 分钟）</p></div>}
      {selected&&<div className="card week-detail"><div><p className="kicker">{WEEKDAY_LABELS[selected.weekday-1]} {selected.startTime}-{selected.endTime}</p><h3>{selected.name}</h3><p className="muted">{[selected.location,selected.teacher,selected.weeks,formatDuration(selected.startTime,selected.endTime)].filter(Boolean).join(' · ')}</p><label className="course-note-label">课程备注</label><textarea className="input course-note" placeholder="给这门课写点备注，例如老师重点、作业、考试范围、上课提醒……" value={selected.note||''} onChange={e=>store.updateCourse(selected.id,{note:e.target.value})} rows={4}/><small className="muted">备注会自动保存到本机，导出备份时也会一起保存。</small></div><div className="row wrap"><button className="btn ghost" onClick={()=>{store.removeCourse(selected.id);setSelectedId(undefined)}}>删除这节</button><button className="btn ghost" onClick={()=>setSelectedId(undefined)}>关闭</button></div></div>}
      <div className="tt-wrap card"><WeekTimetable courses={visibleCourses} exams={store.data.exams} weekStart={weekMonday} now={now} view={view} selectedId={selectedId} offWeekIds={offWeekIds} onSelectCourse={course=>setSelectedId(course.id)} onSelectSlot={slot=>{setWeekday(slot.weekday);setStartTime(slot.startTime);setEndTime(slot.endTime);setShowAdd(true);setSelectedId(undefined);setStatus(`已选 ${WEEKDAY_LABELS[slot.weekday-1]} ${slot.startTime}-${slot.endTime}，补课程名后点「加到课表」`)}} onHideHour={store.toggleHiddenHour} onHideWeekday={store.toggleHiddenWeekday}/></div>
      <ScheduleSettings store={store} open={settingsOpen} onClose={()=>setSettingsOpen(false)}/>
    </>}
    {tab==='import'&&<div className="card"><h3>从表格或图片导入</h3><p className="muted">识别结果会写入当前学期（{currentTerm?termLabel(currentTerm):'未选择'}）。表格（xlsx / xls / csv / ods）在浏览器里直接解析。照片、截图、PDF 走主站 MathCode 同一套视觉模型。</p><input className="input" placeholder="可选：给 AI 的提示，例如「这是大二上学期课表，第1-2节是 08:00-09:40」" value={userHint} onChange={e=>setUserHint(e.target.value)}/><div className="row wrap" style={{marginTop:12}}><label className="btn primary file-btn">{importing?'正在识别…':'选择表格或图片'}<input type="file" hidden accept={TIMETABLE_ACCEPT} disabled={importing} onChange={e=>{const file=e.target.files?.[0];if(file)void onImport(file);e.target.value='' }}/></label><button className="btn ghost" onClick={()=>downloadSample('grid')}>下载课表示例 CSV</button><button className="btn ghost" onClick={()=>downloadSample('exam')}>下载考试表示例 CSV</button><a className="btn ghost" href={`${import.meta.env.BASE_URL}samples/course-grid.png`} download>下载课表示例图片</a>{store.data.courses.length>0&&<button className="btn ghost" onClick={()=>store.clearCourses()}>清空课表</button>}</div>{previewUrl&&<img className="ocr-preview" src={previewUrl} alt="待识别的课表图片"/>}</div>}
    {tab==='exams'&&<div className="card"><h3>考试时间表</h3><div className="row wrap"><input className="input" placeholder="考试名称" value={examName} onChange={e=>setExamName(e.target.value)}/><select className="input slim" value={examKind} onChange={e=>setExamKind(e.target.value as ExamKind)}>{Object.entries(EXAM_KIND_LABEL).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select><input className="input slim" type="date" value={examDate} onChange={e=>setExamDate(e.target.value)}/><TimeInput value={examStart} onChange={setExamStart} label="考试开始"/><TimeInput value={examEnd} onChange={setExamEnd} label="考试结束"/><input className="input slim" placeholder="地点" value={examLoc} onChange={e=>setExamLoc(e.target.value)}/><button className="btn primary" onClick={addExam}>登记考试</button></div><ul className="mini-list">{examsSoon.map(e=><li key={e.id}><strong>{EXAM_KIND_LABEL[e.kind]} · {e.name}</strong> · {e.date} {e.startTime}{e.endTime?`-${e.endTime}`:''} {e.location||''}</li>)}</ul></div>}
    {tab==='remind'&&<div className="card"><h3>提醒</h3><div className="row wrap"><button className="btn ghost" onClick={requestPermission}>允许浏览器通知</button><button className="btn ghost" onClick={tryClassReminder}>预览上课提醒</button><button className="btn ghost" onClick={tryExamReminder}>预览考试提醒</button></div></div>}
  </section>
}
