import { useEffect, useMemo, useRef, useState } from 'react'
import CalendarView from './components/CalendarView'
import Countdowns from './components/Countdowns'
import Notes from './components/Notes'
import Schedule from './components/Schedule'
import ExamTimetable from './components/ExamTimetable'
import SelfManagementTimetable from './components/SelfManagementTimetable'
import Today from './components/Today'
import Todos from './components/Todos'
import AccountCenter from './components/AccountCenter'
import { useAppStore } from './hooks/useAppStore'
import { useAccountSync } from './hooks/useAccountSync'
import { useReminders } from './hooks/useReminders'
import type { View } from './types'
const VIEWS:{id:View;label:string;icon:string}[]=[{id:'today',label:'每日提醒',icon:'☀️'},{id:'calendar',label:'日历',icon:'📅'},{id:'todos',label:'待办',icon:'✦'},{id:'schedule',label:'课表',icon:'📚'},{id:'exams',label:'考试',icon:'📝'},{id:'selfschedule',label:'自律',icon:'⏱️'},{id:'days',label:'倒数日',icon:'🔥'},{id:'notes',label:'便签',icon:'🌸'}]
function parseView():View{const hash=window.location.hash.replace('#','') as View;return VIEWS.some(v=>v.id===hash)?hash:'today'}
export default function App(){const store=useAppStore();const account=useAccountSync(store.data,store.replace,store.ready);const reminders=useReminders(store.data.courses,store.data.exams,store.data.reminderSettings,store.data.todos,store.data.selfSchedules,store.data.calendarEvents,store.data.recurringReminders);const[view,setView]=useState<View>(parseView);const[query,setQuery]=useState('');const[menuOpen,setMenuOpen]=useState(false);const fileRef=useRef<HTMLInputElement>(null);useEffect(()=>{const onHash=()=>setView(parseView());window.addEventListener('hashchange',onHash);return()=>window.removeEventListener('hashchange',onHash)},[]);const open=(next:View)=>{setView(next);window.location.hash=next}
 const hits=useMemo(()=>{const q=query.trim().toLowerCase();if(!q)return null;return{todos:store.data.todos.filter(t=>t.title.toLowerCase().includes(q)),countdowns:store.data.countdowns.filter(c=>c.title.toLowerCase().includes(q)),notes:store.data.notes.filter(n=>n.title.toLowerCase().includes(q)||n.body.toLowerCase().includes(q)),courses:store.data.courses.filter(c=>c.name.toLowerCase().includes(q)||(c.location||'').toLowerCase().includes(q)||(c.teacher||'').toLowerCase().includes(q)),exams:store.data.exams.filter(e=>e.name.toLowerCase().includes(q)||(e.location||'').toLowerCase().includes(q)),self:store.data.selfSchedules.filter(s=>s.title.toLowerCase().includes(q)||(s.note||'').toLowerCase().includes(q)),events:store.data.calendarEvents.filter(e=>e.title.toLowerCase().includes(q)||(e.location||'').toLowerCase().includes(q)||(e.note||'').toLowerCase().includes(q)),recurring:store.data.recurringReminders.filter(r=>r.title.toLowerCase().includes(q)||(r.body||'').toLowerCase().includes(q))}},[query,store.data])
 return <div className="shell"><header className="topbar"><div className="brand"><span className="mark">日</span><div><strong>颗秒日事</strong><p>青春校园 · 粉蓝火焰</p></div></div><nav className="tabs desktop-nav" aria-label="功能">{VIEWS.map(v=><button key={v.id} className={`tab ${view===v.id&&!hits?'active':''}`} onClick={()=>open(v.id)}>{v.label}</button>)}</nav><div className="top-actions"><input className="input search" placeholder="搜索日程、待办、课表、考试、便签" value={query} onChange={e=>setQuery(e.target.value)} aria-label="搜索"/><div className="menu-wrap"><button className="btn ghost" onClick={()=>setMenuOpen(o=>!o)} aria-expanded={menuOpen}>更多</button>{menuOpen&&<div className="menu"><button onClick={()=>{store.downloadBackup();setMenuOpen(false)}}>导出备份</button><button onClick={()=>{fileRef.current?.click();setMenuOpen(false)}}>导入备份</button><button onClick={()=>{if(confirm('清空本机全部日事数据？此操作不可恢复。'))store.clearAll();setMenuOpen(false)}}>清空本机数据</button><a href="https://www.yydsxwh.com/products">返回软件产品</a></div>}</div><AccountCenter account={account} data={store.data}/></div><input ref={fileRef} type="file" accept="application/json" hidden onChange={e=>{const file=e.target.files?.[0];if(file)void store.importBackup(file);e.target.value='' }}/></header>
 {reminders.banner&&<div className={`remind-banner ${reminders.banner.kind}`} role="status"><div><strong>{reminders.banner.title}</strong><p>{reminders.banner.body}</p></div><button className="btn ghost" onClick={reminders.dismiss}>知道了</button></div>}
 <main className="main">{hits?<section className="view"><header className="view-head"><h2>搜索「{query}」</h2><p className="muted">{hits.todos.length+hits.countdowns.length+hits.notes.length+hits.courses.length+hits.exams.length+hits.self.length+hits.events.length+hits.recurring.length} 条结果</p></header><div className="card"><h3>周期性提醒</h3><ul className="mini-list">{hits.recurring.map(r=><li key={r.id}>{r.title}{r.enabled?'':' · 已暂停'}</li>)}</ul><h3>日程</h3><ul className="mini-list">{hits.events.map(e=><li key={e.id}>{e.title} · {e.date} {e.allDay?'全天':`${e.startTime||''}${e.endTime?`-${e.endTime}`:''}`}</li>)}</ul><h3>待办</h3><ul className="mini-list">{hits.todos.map(t=><li key={t.id}><label><input type="checkbox" checked={t.done} onChange={()=>store.toggleTodo(t.id)}/><span>{t.title}</span></label></li>)}</ul><h3>课程</h3><ul className="mini-list">{hits.courses.map(c=><li key={c.id}>{c.name} · {c.startTime}-{c.endTime} {c.location}</li>)}</ul><h3>考试</h3><ul className="mini-list">{hits.exams.map(e=><li key={e.id}>{e.name} · {e.date} {e.startTime}</li>)}</ul><h3>自我管理</h3><ul className="mini-list">{hits.self.map(s=><li key={s.id}>{s.title} · {s.startTime}-{s.endTime}</li>)}</ul><h3>倒数日</h3><ul className="mini-list">{hits.countdowns.map(c=><li key={c.id}>{c.emoji} {c.title}</li>)}</ul><h3>便签</h3><ul className="mini-list">{hits.notes.map(n=><li key={n.id}>{n.title||n.body}</li>)}</ul></div></section>:view==='today'?<Today store={store} onOpen={open}/>:view==='calendar'?<CalendarView store={store}/>:view==='todos'?<Todos store={store}/>:view==='schedule'?<Schedule store={store} requestPermission={reminders.requestPermission} previewReminder={reminders.preview}/>:view==='exams'?<ExamTimetable store={store}/>:view==='selfschedule'?<SelfManagementTimetable store={store}/>:view==='days'?<Countdowns store={store}/>:<Notes store={store}/>}</main>
 <nav className="bottom-nav" aria-label="移动导航">{VIEWS.map(v=><button key={v.id} className={view===v.id&&!hits?'active':''} onClick={()=>open(v.id)}><span className="nav-icon" aria-hidden>{v.icon}</span><span>{v.label}</span></button>)}</nav></div>}
